application:
  name: lexum-app
  database:
    docs-table-name: docs
    database-name: lexum
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration